[package]
name = "apilib"
version = "0.1.0"
authors = ["Mark <mverleg.noreply@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
simple-server = "0.3"

[lib]
name = "apilib"
path = "lib.rs"
