[package]
name = "apilib"
version = "0.1.0"
authors = ["Mark <mverleg.noreply@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[lib]
name = "apilib"
path = "lib.rs"
