[package]
name = "gen_rest_client"
version = "0.1.0"
authors = ["Mark <mverleg.noreply@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
derive-new = "0.5"

[lib]
name = "gen_rest_client"
path = "lib.rs"
